name: fupy
channels:
- conda-forge
- defaults
dependencies:
- python=3.8
- jupyterlab
- numpy
- pandas
- geopandas
- scipy
- matplotlib
- seaborn
- pip
- scikit-learn
- statsmodels
- descartes
- cartopy
- folium
- spyder
- wordcloud
- requests
- beautifulsoup4
- streamlit

- pip:
  - jupyter-book
  - jupyter_sphinx_theme
  - stop-words
  - streamlit-folium
